name: Simple CI

on:
  push:
    branches:
       - main
concurrency:
  group: workflow-simple-group
  cancel-in-progress: true

jobs:  
  install_nodejs:
    runs-on: ubuntu-latest
    if: contains(fromJSON('["push", "pull_request"]'), github.event_name)
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          
        - name: Display test file content
          run: cat test/example.test.js
          
        - name: Setup nodejs version and get dependencies
          uses: actions/setup-node@v4
          with:
            node-version: '14'
            
        # - name: Initialize nodejs en
        #   run: npm init -y
        
        - name: Install mocha dependency
          run: npm install --save-dev mocha chai

        - name: Run tests
          run: npm test >> tests-result-artifact.log

        - name: Create artifact and push it to the repo
          uses: actions/upload-artifact@v3
          with:
            name: tests-result-artifact
            path: tests-result-artifact.log
            # path: /test/result/tests-result-artifact.log
    
  use_custom_action:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Run my custom action
          uses: ./.github/actions/my-action
          with:
            name: "world"
