name: Simple CI

on:
  push:
    branches:
       - main
concurrency:
  group: workflow-simple-group
  cancel-in-progress: true

jobs:  
  install_nodejs:
    runs-on: ubuntu-latest
    if: contains(fromJSON('["push", "pull_request"]'), github.event_name)
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4 
        - name: Install nodejs
          uses: actions/setup-node@v4
          with:
            node-version: '14'  
        - run: npm init -y
        - run: npm install
